---
- name: Configure Loopback Interface on Router104
  gather_facts: no
  host: all
  tasks:
    - name: Show run
      cisco.ios.ios_command:
        commands: 
          - show run
      register: show_run

    - debug: 
        msg: "{{show_run.stdout_lines}}"
