---
- name: Configure Loopback Interface on Router104
  gather_facts: no
  hosts: all
  tasks:
    - name: Show run
      ios_command:
      
        commands: 
          - show run
      register: show_run

    - debug: 
        msg: "{{show_run.stdout_lines}}"
